name: Dependency Update

on:
  schedule:
    - cron: '0 2 * * 1'  # Weekly on Monday at 2 AM
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  update-gradle-dependencies:
    name: Update Gradle Dependencies
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: true
          token: ${{ secrets.GIT_ACTION_TOKEN }}

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: "17"
          distribution: "temurin"
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Update Gradle dependencies
        run: |
          ./gradlew dependencyUpdates -Drevision=release
          ./gradlew wrapper --gradle-version=latest

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.GIT_ACTION_TOKEN }}
          commit-message: 'chore: update gradle dependencies'
          title: 'chore: Update Gradle Dependencies'
          body: |
            ## 📦 Dependency Updates
            
            This PR updates Gradle dependencies to their latest versions.
            
            ### Changes
            - Updated project dependencies
            - Updated Gradle wrapper version
            
            ### Checklist
            - [ ] All tests pass
            - [ ] No breaking changes
            - [ ] Application builds successfully
            
            ---
            *This PR was automatically created by the dependency update workflow.*
          branch: deps/gradle-updates
          delete-branch: true
          assignees: ${{ github.repository_owner }}
          reviewers: ${{ github.repository_owner }}

  update-github-actions:
    name: Update GitHub Actions
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Update actions
        uses: dependabot/fetch-metadata@v2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Create Pull Request for Actions
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.GIT_ACTION_TOKEN }}
          commit-message: 'chore: update github actions'
          title: 'chore: Update GitHub Actions'
          body: |
            ## 🔧 GitHub Actions Updates
            
            This PR updates GitHub Actions to their latest versions.
            
            ### Security
            - Ensures we're using the latest secure versions
            - Addresses any known vulnerabilities
            
            ---
            *This PR was automatically created by the dependency update workflow.*
          branch: deps/actions-updates
          delete-branch: true
          assignees: ${{ github.repository_owner }}
          reviewers: ${{ github.repository_owner }}